services:
  - type: web
    name: synergy-report-tool
    env: python
    plan: free
    buildCommand: ""  # You can leave this blank or use "pip install -r requirements.txt"
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11